version: 2

build:
  os: 'ubuntu-20.04'
  tools:
    python: '3.8'
    
sphinx:
  fail_on_warning: true

python:
  # Install python packages before building the docs
  install:
    - method: pip
      path: .
